#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - bash
  - sudo
  - git
runcmd:
  - [ bash, -c, "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--disable=traefik' INSTALL_K3S_VERSION='v1.31.6+k3s1' sh -" ]
  - [ mkdir, -p, /root/.kube ]
  - [ ln, -sf, /etc/rancher/k3s/k3s.yaml, /root/.kube/config ]
  - [ chmod, 600, /root/.kube/config ]
  - [ bash, -c, "kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.yaml" ]
